$background = rgb(0f1122)
$foreground = rgb(c3c3c7)
$color0 = rgb(0f1122)
$color1 = rgb(1C3292)
$color2 = rgb(2A3C89)
$color3 = rgb(1F39A9)
$color4 = rgb(223CAB)
$color5 = rgb(2E4297)
$color6 = rgb(304AB5)
$color7 = rgb(c3c3c7)
$color8 = rgb(5e6073)
$color9 = rgb(1C3292)
$color10 = rgb(2A3C89)
$color11 = rgb(1F39A9)
$color12 = rgb(223CAB)
$color13 = rgb(2E4297)
$color14 = rgb(304AB5)
$color15 = rgb(c3c3c7)
$wallpaper = swww query | sed -n 's/.*image: \(.*\)$/\1/p'
